name: neurodesk
title: Neurodesk
website: https://github.com/reaudito/NeuroDesk
source-code: https://github.com/reaudito/NeuroDesk
issues: https://github.com/reaudito/NeuroDesk/issues
base: core24
version: "0.3.1"
summary: "Neurodesk: A Lightweight Ollama Client App"
description: |
  Neurodesk: A Lightweight Ollama Client App Built on Tauri and Leptos.
  Install Ollama and make Neurodesk your offline AI assistant.

grade: stable
confinement: strict

layout:
  /usr/lib/x86_64-linux-gnu/webkit2gtk-4.1:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1

apps:
  neurodesk:
    command: usr/bin/neurodesk
    desktop: usr/share/applications/neurodesk.desktop
    extensions: [gnome]
    plugs:
      - network
    # Add whatever plugs you need here, see https://snapcraft.io/docs/snapcraft-interfaces for more info.
    # The gnome extension already includes [ desktop, desktop-legacy, gsettings, opengl, wayland, x11, mount-observe, calendar-service ]
    #  - single-instance-plug # add this if you're using the single-instance plugin
    #slots:
    # Add the slots you need to expose to other snaps
    #  - single-instance-plug # add this if you're using the single-instance plugin

# Add these lines only if you're using the single-instance plugin
# Check https://v2.tauri.app/plugin/single-instance/ for details
#slots:
#  single-instance:
#    interface: dbus
#    bus: session
#    name: org.net_mydomain_MyApp.SingleInstance # Remember to change net_mydomain_MyApp to your app ID with "_" instead of "." and "-"
#
#plugs:
#  single-instance-plug:
#    interface: dbus
#    bus: session
#    name: org.net_mydomain_MyApp.SingleInstance # Remember to change net_mydomain_MyApp to your app ID with "_" instead of "." and "-"

package-repositories:
  - type: apt
    components: [main]
    suites: [noble]
    key-id: 78E1918602959B9C59103100F1831DDAFC42E99D
    url: http://ppa.launchpad.net/snappy-dev/snapcraft-daily/ubuntu

parts:
  build-app:
    plugin: dump
    build-snaps:
      - node/20/stable
      - rustup/latest/stable
    build-packages:
      - libwebkit2gtk-4.1-dev
      - build-essential
      - curl
      - wget
      - file
      - libxdo-dev
      - libssl-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev
      - dpkg
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libayatana-appindicator3-1
    source: .
    override-build: |
      set -eu
      dpkg -x target/release/bundle/deb/neurodesk_0.3.1_amd64.deb $SNAPCRAFT_PART_INSTALL/
      sed -i -e "s|Icon=neurodesk|Icon=/usr/share/icons/hicolor/32x32/apps/neurodesk.png|g" $SNAPCRAFT_PART_INSTALL/usr/share/applications/neurodesk.desktop
